MOSIP-34308
mosip/resident-services pull request #1314
Opened 2024-08-08 10:25 UTC by damodarguru

Added descriptions for resident module

2024-08-28 12:43 UTC, nandhu-kumar requested changes

2024-08-28 12:43 UTC, nandhu-kumar commented on apitest/src/main/resources/resident/AddIdentity/AddIdentity.yml
Please remove special characters in the description. i.e - (VID)

2024-08-28 12:43 UTC, nandhu-kumar commented on apitest/src/main/resources/resident/AuthHistory/AuthHistory.yml
> +      description: Retrieve authentication history based on a resident's unique identification number (UIN)
please remove special characters.

2024-09-23 05:10 UTC, nandhu-kumar approved these changes

2024-09-23 07:02 UTC, mohanachandran-s approved these changes

2024-09-23 07:44 UTC, merged