unique_identifier
mosip/resident-services pull request #1357
Opened 2024-11-11 12:10 UTC by damodarguru

2024-11-11 12:45 UTC, nandhu-kumar commented on api-test/mosip-api-internal.qa-plan-resident-2024-10-22_16-28-report_T-1108_P-542_S-78_F-488.html
please remove the report

2024-11-11 12:45 UTC, nandhu-kumar commented on api-test/mosip-api-internal.qa-plan-resident-prerequisite-2024-10-22_16-25-report_T-30_P-30_S-0_F-0.html
please remove the report

2024-11-11 13:09 UTC, nandhu-kumar approved these changes

2024-11-11 13:32 UTC, mohanachandran-s requested changes

2024-11-11 13:32 UTC, mohanachandran-s commented on api-test/src/main/resources/resident/GenerateVID/createGenerateVID.yml
> +      uniqueIdentifier: TC_Resident_Generate_
This line has to be removed, duplicate line

2024-11-12 04:16 UTC, mohanachandran-s requested changes

2024-11-12 04:16 UTC, mohanachandran-s commented on api-test/src/main/resources/resident/CredentialIssuance/CancellCredential/CancellCredential.yml
> +      uniqueIdentifier: TC_Resident_CredentialsStatus
this identifier should be TC_Resident_CredentialsStatus_01

2024-11-12 04:16 UTC, mohanachandran-s commented on api-test/src/main/resources/resident/GenerateToken/GenerateToken.yml
> +      uniqueIdentifier: Dependent_ESignet
This unique identifier should be appropriate

2024-11-12 04:16 UTC, mohanachandran-s commented on api-test/src/main/resources/resident/GenerateToken/GenerateToken.yml
> +      uniqueIdentifier: Dependent_ESignet
This unique identifier should be appropriate

2024-11-12 04:16 UTC, mohanachandran-s commented on api-test/src/main/resources/resident/GenerateVID/createGenerateVID.yml
> +      uniqueIdentifier: TC_Resident_Generate_01
This should be TC_Resident_GenerateVID_01

2024-11-12 04:16 UTC, mohanachandran-s commented on api-test/src/main/resources/resident/GenerateVID/createGenerateVID.yml
This should be TC_Resident_GenerateVID for entire file

2024-11-12 04:16 UTC, mohanachandran-s commented on api-test/src/main/resources/resident/GenerateVID/createGenerateVIDNew.yml
Unique identifier should be TC_Resident_GenerateVID for entire file

2024-11-12 11:05 UTC, mohanachandran-s approved these changes

2025-01-28 08:27 UTC, ckm007 approved these changes

2025-01-28 12:39 UTC, merged