MOSIP-18026: migrate from apache to kernelcore util base64
mosip/resident-services pull request #155
Opened 2021-10-20 10:15 UTC by abuabdul

2021-10-20 18:06 UTC, vishwa-vyom requested changes

2021-10-20 18:06 UTC, vishwa-vyom commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/ResidentCredentialServiceImpl.java
> +			byte[] pdfBytes = CryptoUtil.decodePlainBase64(responseObject.getResponse().getData());
I think this needs to be decode using the url safe, how did we conclude on plain base 64 decoding ?

2021-10-20 18:06 UTC, vishwa-vyom commented on resident/resident-service/src/main/java/io/mosip/resident/util/EncryptorUtil.java
>              cryptomanagerRequestDto.setTimeStamp(DateUtils.getUTCCurrentDateTime());
I see line #93 of this file still uses the deprecated encode and decode methods

2021-10-21 06:15 UTC, vishwa-vyom commented on resident/resident-service/src/main/java/io/mosip/resident/handler/service/ResidentUpdateService.java
> +		docDetailsDto.setDocument(CryptoUtil.decodePlainBase64(documentBytes));
Checked with Rounak, above 2 also needs to be url safe decoding. Looks like they have not update the docs.

2021-10-21 07:17 UTC, abuabdul commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/ResidentCredentialServiceImpl.java
> +			byte[] pdfBytes = CryptoUtil.decodePlainBase64(responseObject.getResponse().getData());
I updated to urlsafe decode method after our discussion. it works fine.

2021-10-21 07:18 UTC, abuabdul commented on resident/resident-service/src/main/java/io/mosip/resident/util/EncryptorUtil.java
>              cryptomanagerRequestDto.setTimeStamp(DateUtils.getUTCCurrentDateTime());
After discussion with Taheer, encrypt service is using urlsafe methods. So we have updated the same in our resident services too.

2021-10-21 07:18 UTC, abuabdul commented on resident/resident-service/src/main/java/io/mosip/resident/handler/service/ResidentUpdateService.java
> +		docDetailsDto.setDocument(CryptoUtil.decodePlainBase64(documentBytes));
I have updated these as urlsafe methods.

2021-10-21 07:32 UTC, vishwa-vyom requested changes

2021-10-21 07:32 UTC, vishwa-vyom commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/ResidentServiceImpl.java
> +			byte[] decodedDemoJson = CryptoUtil.decodePlainBase64(dto.getIdentityJson());
if ResidentUpdateService.java is doing url safe, the same should be used here since this dto is loaded from the same request object

2021-10-21 08:01 UTC, abuabdul commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/ResidentServiceImpl.java
> +			byte[] decodedDemoJson = CryptoUtil.decodePlainBase64(dto.getIdentityJson());
You are right. I have updated.

2021-10-21 09:46 UTC, vishwa-vyom approved these changes

2021-10-21 09:46 UTC, merged