fixed the response for new UIN
mosip/resident-services pull request #527
Opened 2022-10-18 07:22 UTC by RitikJain4108

2022-10-18 12:10 UTC, gsasikumar requested changes

2022-10-18 12:10 UTC, gsasikumar commented on resident/resident-service/src/main/java/io/mosip/resident/controller/ResidentController.java
> +		ResponseWrapper<AuthLockStatusResponseDtoV2> responseWrapper = new ResponseWrapper<>();
Is the response changing? was this api as part of 1.2.0?
if so we can not make changes. We need to introduce a new api. If this is a new api then i can allow it.

2022-10-19 07:19 UTC, RitikJain4108 commented on resident/resident-service/src/main/java/io/mosip/resident/controller/ResidentController.java
> +		ResponseWrapper<AuthLockStatusResponseDtoV2> responseWrapper = new ResponseWrapper<>();
yes, there is some changes required in response and it is a part of 1.2.1

2022-10-19 11:35 UTC, gsasikumar approved these changes

2022-10-19 11:35 UTC, merged