MOSIP-22851 Changes in identity info API
mosip/resident-services pull request #528
Opened 2022-10-19 14:09 UTC by Neha2365

2022-10-21 08:01 UTC, LoganathanSekar7627 requested changes

2022-10-21 08:01 UTC, loganathan-sekaran commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/IdentityServiceImpl.java
> +			Map<?, ?> identity = (Map<?, ?>) getIdentityAttributes(id, type, true,UISchemaTypes.UPDATE_DEMOGRAPHICS.getFileIdentifier());
Pass the schematype here by getting it from a new method argument.

2022-10-21 08:01 UTC, loganathan-sekaran commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/IdentityServiceImpl.java
> +		 identity.put("photo", identityDTO.getFace());
Use "photo" from a constant and use in all related places.

2022-10-21 08:01 UTC, loganathan-sekaran commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/ResidentConfigServiceImpl.java
> +		if(schemaType.equalsIgnoreCase(UISchemaTypes.PERSONALIZED_CARD.getFileIdentifier())) {
No need for if condition here, whatever schema type comes you can pass it in the getUISchema method, because no need to add another condition if one more schema type comes.

2022-10-21 08:01 UTC, LoganathanSekar7627 commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/IdentityServiceImpl.java
> +			Map<?, ?> identity = (Map<?, ?>) getIdentityAttributes(id, type, true,UISchemaTypes.UPDATE_DEMOGRAPHICS.getFileIdentifier());
The caller has to pass the schema type.

2022-10-21 09:34 UTC, Neha2365 commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/ResidentConfigServiceImpl.java
> +		if(schemaType.equalsIgnoreCase(UISchemaTypes.PERSONALIZED_CARD.getFileIdentifier())) {
Changes done

2022-10-25 11:12 UTC, LoganathanSekar7627 approved these changes

2022-10-25 11:17 UTC, Neha2365 commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/IdentityServiceImpl.java
> +		 identity.put("photo", identityDTO.getFace());
Changes done

2022-10-25 11:17 UTC, Neha2365 commented on resident/resident-service/src/main/java/io/mosip/resident/service/impl/IdentityServiceImpl.java
> +			Map<?, ?> identity = (Map<?, ?>) getIdentityAttributes(id, type, true,UISchemaTypes.UPDATE_DEMOGRAPHICS.getFileIdentifier());
Changes done

2022-10-25 11:28 UTC, merged